server:
  port: 8080
  context-path: /dianying
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dianying?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB    
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mappers/*.xml
  type-aliases-package: com.model
logging:
    level:
      com.mapper: debug
